In [3]:
!pip3 install numpy


# Numpy


#### Numpy

-Numpy


- Numpy


In [5]:
import numpy as np

In [6]:
arr=np.array([[1,2,3],[4,5,6]])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.ndim # no of dimentions

2

In [9]:
arr.shape 

(2, 3)

In [10]:
ar1=np.array([1,2,3])

In [11]:
ar1.shape #for 1D array o/p is like (n,)->n refers to no of elements

(3,)

In [13]:
arr.size #no of elements

6

In [14]:
arr.dtype #data type of objects

dtype('int32')

In [15]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
# can create numpy array from list and tuple

In [18]:
b=np.zeros((3,2))

In [19]:
b

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
c=np.ones((2,1))

In [21]:
c

array([[1.],
       [1.]])

In [22]:
d=np.eye(3,3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [154]:
e=np.arange(0,10,2) # 5 is step size
e

array([0, 2, 4, 6, 8])

In [27]:
f=np.linspace(0,30,9) # 9 is the no of elements
f

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  , 18.75, 22.5 , 26.25, 30.  ])

In [31]:
g=np.random.random((3,2)) # creates elements with random values
g

array([[0.09427588, 0.37994585],
       [0.23956708, 0.3686166 ],
       [0.25303184, 0.01176232]])

In [33]:
h=arr.reshape(3,2)
e=arr.reshape(1,6)
h,e

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[1, 2, 3, 4, 5, 6]]))

In [36]:
f=arr.flatten() # convert nD into 1D
f

array([1, 2, 3, 4, 5, 6])

In [49]:
a1=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12],
            [13,14,15,16]])

In [53]:
a2=a1[1:3,1:3]
a2

array([[ 6,  7],
       [10, 11]])

In [54]:
a3=a1[1::2,::3] #2 and 3 are step sizes
a3

array([[ 5,  8],
       [13, 16]])

In [55]:
a4=a1[:,:3:2] #here 2 is step size
a4

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

In [69]:
cond=(a1 > 4)
t=a1[cond]
t

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [71]:
# broadcasting feature
d=a1+1
d

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [76]:
e=a1.T #transpose of array
e

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [79]:
print(a1.max())      # total maximum of array
print(a1.max(axis=1)) # axis =1 implies max row wise
a1.max(axis=0)        # axis =0 implies max column wise

16
[ 4  8 12 16]


array([13, 14, 15, 16])

In [80]:
a1.sum()

136

In [101]:
a=np.array([[1,2,3],[3,4,5],[5,6,7]])
c=np.array([[1,0,0],[0,1,0],[0,0,1]])
b=np.eye(3,3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [103]:
print("array multiplication :",a*b)
print("matrix multiplication :",a.dot(b))

array multiplication : [[1. 0. 0.]
 [0. 4. 0.]
 [0. 0. 7.]]
matrix multiplication : [[1. 2. 3.]
 [3. 4. 5.]
 [5. 6. 7.]]


In [104]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.95892427, -0.2794155 ,  0.6569866 ]])

In [105]:
np.exp(a)

array([[   2.71828183,    7.3890561 ,   20.08553692],
       [  20.08553692,   54.59815003,  148.4131591 ],
       [ 148.4131591 ,  403.42879349, 1096.63315843]])

In [107]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [1.73205081, 2.        , 2.23606798],
       [2.23606798, 2.44948974, 2.64575131]])

In [108]:
np.sort(a)

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [113]:
np.sort(b,axis=0,kind="merge sort")

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.]])

- stacking and splitting

In [117]:
np.vstack((a,b))

array([[1., 2., 3.],
       [3., 4., 5.],
       [5., 6., 7.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [118]:
np.hstack((a,b))

array([[1., 2., 3., 1., 0., 0.],
       [3., 4., 5., 0., 1., 0.],
       [5., 6., 7., 0., 0., 1.]])

In [121]:
np.concatenate((a,b))

array([[1., 2., 3.],
       [3., 4., 5.],
       [5., 6., 7.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [122]:
np.concatenate((a,b),1)

array([[1., 2., 3., 1., 0., 0.],
       [3., 4., 5., 0., 1., 0.],
       [5., 6., 7., 0., 0., 1.]])

In [130]:
np.hsplit(a,3)

[array([[1],
        [3],
        [5]]),
 array([[2],
        [4],
        [6]]),
 array([[3],
        [5],
        [7]])]

In [131]:
np.vsplit(a,3)

[array([[1, 2, 3]]), array([[3, 4, 5]]), array([[5, 6, 7]])]

In [133]:
help(np.array_split)

Help on function array_split in module numpy:

array_split(ary, indices_or_sections, axis=0)
    Split an array into multiple sub-arrays.
    
    Please refer to the ``split`` documentation.  The only difference
    between these functions is that ``array_split`` allows
    `indices_or_sections` to be an integer that does *not* equally
    divide the axis. For an array of length l that should be split
    into n sections, it returns l % n sub-arrays of size l//n + 1
    and the rest of size l//n.
    
    See Also
    --------
    split : Split array into multiple sub-arrays of equal size.
    
    Examples
    --------
    >>> x = np.arange(8.0)
    >>> np.array_split(x, 3)
        [array([0.,  1.,  2.]), array([3.,  4.,  5.]), array([6.,  7.])]
    
    >>> x = np.arange(7.0)
    >>> np.array_split(x, 3)
        [array([0.,  1.,  2.]), array([3.,  4.]), array([5.,  6.])]



In [143]:
np.array_split(a,3)

[array([[1, 2, 3]]), array([[3, 4, 5]]), array([[5, 6, 7]])]

# More statistical functions

- min,max
- mean,average
- median
- varience (var)
- standard deviation (std)
- abs0lute (abs)

In [145]:
np.average(a,weights=b) # (a1*b1 + a2*b2 + ...)/(n1+n2)

4.0

In [147]:
np.median(a)

4.0

In [149]:
np.var(a)

3.3333333333333335

In [150]:
np.std(a)

1.8257418583505538

# Numpy Random Module

- rand : random values in given shape
- randn : return a sample/ samples from standard normal distribution
- randint : randaon integers from low to high
- random : randon floats in half open interval [0.0, 1.0)
- choice : random samples from 1D array
- shuffle : suffles the contents of sequence

In [157]:
a = np.arange(10) + 2
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [160]:
np.random.shuffle(a)
a

array([ 4, 11,  8,  6,  2,  5,  3,  9, 10,  7])

In [163]:
b=np.random.randn(2,3)
b

array([[ 0.25759352, -1.9593946 , -1.50780766],
       [-0.31529207,  0.85817886,  0.07134299]])

In [176]:
c=np.random.randint(1,100,3)
c

array([71, 22, 50])

In [184]:
d=8*np.random.random((2,3)) # rndm values 0-8 (2X3)
d

array([[4.98688093, 0.12656994, 7.43549787],
       [5.52717534, 7.9785828 , 1.37872407]])

In [183]:
f=8*(np.random.rand(2,3)) # rndm values 0-8 (2X3)
f

array([[4.93715931, 2.61315921, 4.21646482],
       [7.08753679, 2.85815808, 7.26828121]])